# Generated by Django 5.2.7 on 2025-11-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="gestion.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chequeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntos", models.JSONField()),
                ("total", models.IntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                ("resultado", models.CharField(default="En evaluación", max_length=20)),
                (
                    "evaluador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.usuario",
                    ),
                ),
                (
                    "turno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chequeo",
                        to="gestion.turno",
                    ),
                ),
            ],
        ),
    ]
