# Generated by Django 5.2.7 on 2025-11-11 18:55

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_turno_chequeo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chequeo",
            name="puntos",
            field=models.JSONField(default=gestion.models.puntos_por_defecto),
        ),
    ]
