# Generated by Django 5.2.7 on 2025-11-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_alter_chequeo_puntos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporteestado",
            name="vehiculo",
        ),
        migrations.DeleteModel(
            name="Mantenimiento",
        ),
        migrations.DeleteModel(
            name="ReporteEstado",
        ),
    ]
